apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-data-apiserver
spec:
  replicas: 1
  selector:
    matchLabels:
      name: storage-data-apiserver
  template:
    metadata:
      labels:
        name: storage-data-apiserver
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: storage-data-apiserver
          image: ketidevit2/storage-data-apiserver:v0.0.1
          command:
          - storage-data-apiserver
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: INFLUX_IP
              value: "10.0.4.85"
            - name: INFLUX_PORT
              value: "30002"
            - name: INFLUX_USERNAME
              value: "keti"
            - name: INFLUX_PASSWORD
              value: "ketilinux"
            - name: MYSQL_IP
              value: "10.0.4.85"
            - name: MYSQL_PORT
              value: "30001"
            - name: MYSQL_USERNAME
              value: "root"
            - name: MYSQL_PASSWORD
              value: "ketilinux"
            - name: OPERATOR_NAME
              value: "storage-data-apiserver"
      tolerations:
        - key: node.kubernetes.io/not-ready
          effect: NoExecute
          tolerationSeconds: 0
        - key: node.kubernetes.io/unreachable
          effect: NoExecute
          tolerationSeconds: 0
