apiVersion: v1
kind: Service
metadata:
  name: storage-data-apiserver
  labels:
    name: storage-data-apiserver
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30008
    protocol: TCP
  selector:
    name: storage-data-apiserver
