apiVersion: v1
kind: Service
metadata:
  name: csd-metric-interface
  namespace: storage-platform
  labels:
    name: csd-metric-interface
    namespace: storage-platform
spec:
  type: NodePort
  ports:
  - name: csd-metric-interface
    port: 40800
    targetPort: 40800
    nodePort: 30004
    protocol: TCP
  - name: node-metric-collector
    port: 80
    targetPort: 8080
    nodePort: 32544
    protocol: TCP
  selector:
    name: csd-metric-interface
    namespace: storage-platform
