apiVersion: v1
kind: ServiceAccount
metadata:
  name: csd-metric-interface
  namespace: storage-platform
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csd-metric-interface
subjects:
- kind: ServiceAccount
  name: csd-metric-interface
  namespace: storage-platform
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
