// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: wal_manager.proto

#include "wal_manager.pb.h"
#include "wal_manager.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace wal_manager {

static const char* WalManager_method_names[] = {
  "/wal_manager.WalManager/process_query",
};

std::unique_ptr< WalManager::Stub> WalManager::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< WalManager::Stub> stub(new WalManager::Stub(channel, options));
  return stub;
}

WalManager::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_process_query_(WalManager_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status WalManager::Stub::process_query(::grpc::ClientContext* context, const ::wal_manager::query_req& request, ::wal_manager::query_res* response) {
  return ::grpc::internal::BlockingUnaryCall< ::wal_manager::query_req, ::wal_manager::query_res, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_process_query_, context, request, response);
}

void WalManager::Stub::async::process_query(::grpc::ClientContext* context, const ::wal_manager::query_req* request, ::wal_manager::query_res* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::wal_manager::query_req, ::wal_manager::query_res, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_process_query_, context, request, response, std::move(f));
}

void WalManager::Stub::async::process_query(::grpc::ClientContext* context, const ::wal_manager::query_req* request, ::wal_manager::query_res* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_process_query_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::wal_manager::query_res>* WalManager::Stub::PrepareAsyncprocess_queryRaw(::grpc::ClientContext* context, const ::wal_manager::query_req& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::wal_manager::query_res, ::wal_manager::query_req, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_process_query_, context, request);
}

::grpc::ClientAsyncResponseReader< ::wal_manager::query_res>* WalManager::Stub::Asyncprocess_queryRaw(::grpc::ClientContext* context, const ::wal_manager::query_req& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncprocess_queryRaw(context, request, cq);
  result->StartCall();
  return result;
}

WalManager::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      WalManager_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< WalManager::Service, ::wal_manager::query_req, ::wal_manager::query_res, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](WalManager::Service* service,
             ::grpc::ServerContext* ctx,
             const ::wal_manager::query_req* req,
             ::wal_manager::query_res* resp) {
               return service->process_query(ctx, req, resp);
             }, this)));
}

WalManager::Service::~Service() {
}

::grpc::Status WalManager::Service::process_query(::grpc::ServerContext* context, const ::wal_manager::query_req* request, ::wal_manager::query_res* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace wal_manager

