apiVersion: v1
kind: Service
metadata:
  name: opencsd-storage-manager
  namespace: storage-controller
  labels:
    name: opencsd-storage-manager
    namespace: storage-controller
spec:
  type: NodePort
  ports:
    - port: 40307
      targetPort: 40307
      nodePort: 30307
      protocol: TCP
  selector:
    name: opencsd-storage-manager
    namespace: storage-controller
